name: RECOVERY

on:
  workflow_dispatch:
    inputs:
      RECOVERY_URL:
        description: 'RECOVERY URL'
        required: true
        default: 'https://files.catbox.moe/(RECOMMENDED)'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check Out
      uses: actions/checkout@v4

    - name: Prepare the environment
      run: |
        sudo apt install git wget lz4 tar openssl python3 -y

    - name: Fetch image from URL
      run: |
        ls
        pwd
        wget ${{ github.event.inputs.RECOVERY_URL }} -O recovery.img

    - name: Patch Process-1
      run: |
        chmod a+x script1.sh
        chmod a+x magiskboot
        ./script1.sh recovery.img || true

    - name: Patch Process-2
      run: |
        set -e
    
        chmod a+x script2.sh
        ./script2.sh || true
    
        python3 avbtool extract_public_key --key phh.pem --output phh.pub.bin
    
        # Detect patched image
        if [ -f r-patched.img ]; then
          PATCHED_IMG=r-patched.img
        elif [ -f new-boot.img ]; then
          PATCHED_IMG=new-boot.img
        else
          echo "âŒ No patched image found!"
          ls -lh
          exit 1
        fi
    
        echo "Using patched image: $PATCHED_IMG"
    
        python3 avbtool add_hash_footer \
          --partition_name recovery \
          --partition_size $(wc -c recovery.img | cut -f 1 -d ' ') \
          --image "$PATCHED_IMG" \
          --key phh.pem \
          --algorithm SHA256_RSA4096
    
        mkdir -p output
        mv "$PATCHED_IMG" output/recovery.img
    
        cd output
        tar cvf fastbootd-recovery.tar recovery.img
        md5sum -t fastbootd-recovery.tar >> fastbootd-recovery.tar
        mv fastbootd-recovery.tar fastbootd-recovery.tar.md5


    - name: Upload to Release
      uses: softprops/action-gh-release@v2
      with:
        files: output/*.md5
        name: Patched-Recovery
        tag_name: ${{ github.run_id }}
